### PR TITLE
Implement new API methods

### PR DESCRIPTION
**Pull request by ewaltman**
I've implemented 5 new methods for the currently unsupported SurveyMonkey API endpoints. I've made some necessary changes to the URI-building helper functions to support variable resource types, and I've standardized the code format a bit.

### CODE REVIEW

**Comment by oori** [comment]
Thanks for this PR !     I quickly looked at your additions, it looks good, but I couldn't test it at the moment.      Please confirm you've successfully tested **all** methods (with/without optional params).

**Comment by ewaltman** [comment]
No problem - I've tested the methods that I wrote, but I'll run a few more tests for good measure to confirm that everything's functional with/without the optional params!

**Comment by ewaltman** [comment]
Hi @oori ,
I've now pushed 2 more commits, the last of which includes tests for both new and existing endpoints with and without optional params. If you want to confirm that all tests are successful, you just have to fill in your API Key, token, and survey/collector/recipient ids.

**Comment by oori** [comment]
@ewaltman Really sorry for the delay...   at the time you pushed it, I was on a long long vacation,  and since it slipped.      
I just looked into it,  and tried your updated methods and tests,  I will add some small fixed, but all in all it seems to work well.    
Thanks!   and sorry again for the delay.

**Comment by oori** [comment]
@ewaltman FYI:  I've revised the tests, see tests folder and readme.
only missing is the "email flow" tests,  as yours fail *(seems SM changed the requirements)*,   I'll make fix them tomorrow.

Thanks again for you PR.

**Pull request merged**
